#!/usr/bin/env bash
# scripts/demo-schema.sh — bootstrap a vault schema and copy fixtures for DevHarness (PR05).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export PATH="/opt/swift/usr/bin:${PATH:-}"

if ! command -v swift >/dev/null 2>&1; then
  echo "error: swift not found on PATH. Install toolchain (see AGENTS.md)." >&2
  exit 1
fi

DEMO_PARENT="${LOCI_VAULT_PARENT:-}"
if [[ -z "$DEMO_PARENT" ]]; then
  DEMO_PARENT="$(mktemp -d /tmp/loci-schema-demo.XXXXXX)"
fi
export LOCI_VAULT_PARENT="$DEMO_PARENT"

echo "==> loci-vault-demo (schema bootstrap; parent: $LOCI_VAULT_PARENT)"
swift run --package-path "$ROOT" loci-vault-demo

VAULT_ROOT="$DEMO_PARENT/LociVault"
FIXTURE_DIR="$ROOT/DevHarness/public/demo-schema"
mkdir -p "$FIXTURE_DIR/types"

if [[ ! -f "$VAULT_ROOT/.loci/space.json" ]]; then
  echo "error: expected $VAULT_ROOT/.loci/space.json after demo" >&2
  exit 1
fi
if [[ ! -f "$VAULT_ROOT/.loci/types/page.json" ]]; then
  echo "error: expected $VAULT_ROOT/.loci/types/page.json after demo" >&2
  exit 1
fi

cp "$VAULT_ROOT/.loci/space.json" "$FIXTURE_DIR/space.json"
cp "$VAULT_ROOT/.loci/types/page.json" "$FIXTURE_DIR/types/page.json"

# Manifest the Types harness can fetch in one request.
python3 - <<PY
import json
from pathlib import Path
root = Path("$FIXTURE_DIR")
space = json.loads((root / "space.json").read_text())
page = json.loads((root / "types" / "page.json").read_text())
manifest = {
    "space": space,
    "types": [page],
    "note": "Generated by scripts/demo-schema.sh — per-type files under .loci/types/",
}
(root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print("wrote", root / "manifest.json")
PY

echo "==> fixtures:"
echo "  $FIXTURE_DIR/space.json"
echo "  $FIXTURE_DIR/types/page.json"
echo "  $FIXTURE_DIR/manifest.json"
echo "==> demo-schema complete"
