#!/usr/bin/env bash
# scripts/demo-types.sh — custom type + object fixture for DevHarness (PR12).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export PATH="/opt/swift/usr/bin:${PATH:-}"

if ! command -v swift >/dev/null 2>&1; then
  echo "error: swift not found on PATH. Install toolchain (see AGENTS.md)." >&2
  exit 1
fi

OUT_DIR="$ROOT/DevHarness/public/demo-types"
mkdir -p "$OUT_DIR"

echo "==> loci-types-demo"
swift run --package-path "$ROOT" loci-types-demo > "$OUT_DIR/types.json"

python3 - <<'PY'
import json, pathlib
root = pathlib.Path("DevHarness/public/demo-types")
data = json.loads((root / "types.json").read_text())
assert data.get("appearsOnlyUnderBooks") is True, "Deep Work must appear only under Books"
assert data.get("pageDeleteBlocked") is True, "Page delete must be guarded"
assert data.get("objectsFolderExists") is True, "objects/book/ must exist"
types = data.get("types") or []
ids = {t.get("id") for t in types}
assert "book" in ids and "page" in ids and "daily" in ids, f"unexpected types {ids}"
book = data.get("bookObject") or {}
assert book.get("title") == "Deep Work", book
assert str(book.get("relativePath", "")).startswith("objects/book/"), book
print(
    f"types={len(types)} books={data.get('booksCount')} pages={data.get('pagesCount')} "
    f"onlyUnderBooks={data.get('appearsOnlyUnderBooks')} pageDeleteBlocked={data.get('pageDeleteBlocked')}"
)
PY

# Also refresh demo-schema manifest so Types panel shows custom type alongside Page/Daily.
SCHEMA_DIR="$ROOT/DevHarness/public/demo-schema"
mkdir -p "$SCHEMA_DIR/types"
python3 - <<'PY'
import json, pathlib
types_data = json.loads(pathlib.Path("DevHarness/public/demo-types/types.json").read_text())
schema = pathlib.Path("DevHarness/public/demo-schema")
# Keep space.json if present; otherwise synthesize.
space_path = schema / "space.json"
if space_path.exists():
    space = json.loads(space_path.read_text())
else:
    space = {"name": "Demo Custom Types", "schemaVersion": 1, "pins": []}
    space_path.write_text(json.dumps(space, indent=2) + "\n")

types = types_data.get("types") or []
# Write per-type stubs for harness browsing.
types_dir = schema / "types"
types_dir.mkdir(parents=True, exist_ok=True)
for t in types:
    slug = t.get("id") or "unknown"
    (types_dir / f"{slug}.json").write_text(json.dumps(t, indent=2) + "\n")

manifest = {
    "space": space,
    "types": types,
    "customDemo": {
        "bookObject": types_data.get("bookObject"),
        "appearsOnlyUnderBooks": types_data.get("appearsOnlyUnderBooks"),
        "objectsFolder": types_data.get("objectsFolder"),
        "pageDeleteBlocked": types_data.get("pageDeleteBlocked"),
    },
    "note": "Generated by scripts/demo-types.sh — custom Books type + Deep Work object (PR12).",
}
(schema / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print("wrote", schema / "manifest.json")
PY

echo "==> wrote $OUT_DIR/types.json"
echo "==> refreshed DevHarness/public/demo-schema/manifest.json"
echo "==> demo-types complete"
